services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ..
      dockerfile: ./apps/server/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookstore
      - JWT_SECRET=secret
      # - HOST=0.0.0.0
    depends_on:
      - mongo

  client:
    build:
      context: ..
      dockerfile: ./apps/client/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - server

volumes:
  mongo-data:
